import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Inter } from 'next/font/google';
import { Roboto } from 'next/font/google';

const inter = Inter({
  subsets: ['latin'], // Include subsets you need
});
// Configure the Roboto font
const roboto = Roboto({
  subsets: ['latin'], // Include specific subsets
  weight: ['400', '500', '700'], // Specify weights
  variable: '--font-roboto', // Custom CSS variable (optional)
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="inter.className ${roboto.variable}">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
